// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddBookmarkRequest struct {
	Name     *string `json:"name,omitempty"`
	Grape    *string `json:"grape,omitempty"`
	Region   *string `json:"region,omitempty"`
	Location *string `json:"location,omitempty"`
}

type Bookmark struct {
	Name     *string `json:"name,omitempty"`
	Grape    *string `json:"grape,omitempty"`
	Region   *string `json:"region,omitempty"`
	Location *string `json:"location,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UploadImageRequest struct {
	Base64Encoding string `json:"base64Encoding"`
}

type UploadImageResponse struct {
	PublicURL string `json:"publicURL"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
